.\" Copyright (c) 2026 The FreeBSD Foundation
.\"
.\" This man page was written by Minsoo Choo under sponsorship from the FreeBSD
.\" Foundation.
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd January 19, 2026
.Dt QUEUE 3
.Os
.Sh NAME
.In sys/queue.h
.Nd implementations of singly-linked lists, singly-linked tail queues,
lists and tail queues
.Sh DESCRIPTION
.In sys/queue.h
provides macros that define and operate on four types of data structures which
can be used in both C and C++ source code:
.Bl -tag -width "Xr bitstring 3"
.It Xr list 3
Doubly-linked lists
.It Xr slist 3
Singly-linked lists
.It Xr stailq 3
Singly-linked tail queues
.It Xr tailq 3
Tail queues
.El
.Sh SEE ALSO
.Xr arb 3 ,
.Xr list 3 ,
.Xr slist 3 ,
.Xr stailq 3 ,
.Xr tailq 3 ,
.Xr tree 3
.Sh HISTORY
The
.Nm queue
functions first appeared in
.Bx 4.4 .
